# Generated by Django 5.2.7 on 2025-12-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_mock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mocklocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
