# Generated by Django 5.2 on 2025-12-04 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ingredients', models.TextField()),
                ('veg_or_non_veg', models.CharField(choices=[('VEG', 'Veg'), ('NON_VEG', 'Non-Veg')], default='VEG', max_length=10)),
                ('preparation_time', models.PositiveIntegerField(help_text='Preparation time in minutes')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('is_available', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
